// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3UDLNK9ERBZBkJjt5zXH9a1RJtr2IFw',
    appId: '1:369602602226:android:fd037a4edcae7c07911c6b',
    messagingSenderId: '369602602226',
    projectId: 'hc-morocco-doctors',
    storageBucket: 'hc-morocco-doctors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBQ0i2_Itiha5MvsMRCzybvS4v5lcb2Y',
    appId: '1:369602602226:ios:7e57755dfdb69350911c6b',
    messagingSenderId: '369602602226',
    projectId: 'hc-morocco-doctors',
    storageBucket: 'hc-morocco-doctors.appspot.com',
    androidClientId: '369602602226-bp1lufm4nq275kc4acf4rq3t1dr299hv.apps.googleusercontent.com',
    iosClientId: '369602602226-dcj2t28c4jfincm3cnpvla7vanr5568b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hcMoroccoDoctors',
  );
}
